### PR TITLE
Added unit tests and remove inappropriate debugging code.

### PR DESCRIPTION
**Pull request by ledyba-z**
Hi.

I added small (but many) test images and write XCTest cases (using TravisCI and codecov).
 - [Travis CI result](https://travis-ci.org/link-u/SDWebImageAVIFCoder/builds/650771179)
 - [Codecov Result](https://codecov.io/gh/link-u/SDWebImageAVIFCoder/tree/03ef2d8caf3f102a172f3a9932a0a8fa830f490c)

Currently, [it covers 70.36% of `SDWebImageAVIFCoder/Classes/SDImageAVIFCoder.m`](https://codecov.io/gh/link-u/SDWebImageAVIFCoder/src/03ef2d8caf3f102a172f3a9932a0a8fa830f490c/SDWebImageAVIFCoder/Classes/SDImageAVIFCoder.m).

And in this process, I found a bug.
This line is for debugging vImage frameworks, and it should be removed(sorry...):

https://github.com/SDWebImage/SDWebImageAVIFCoder/pull/10/commits/c5e69f95029cfafa7641b8b0b7b0af5b035cb2e5#diff-80940c04bc7eacf6576a4e46ebecd2b2L287

Please take a look!

### CODE REVIEW

**Comment by ledyba-z** [comment]
I think [CI with more complex images (using Github Actions)](https://github.com/SDWebImage/SDWebImageAVIFCoder/actions/runs/39851185) is also still helpful.

**Comment by dreampiggy** [comment]
Actually this is OK.

The test images forcus on the AVIF standard check. It's only because this library already beyond just a simple libavif client (Which I wrote before) :)

For a stable AVIF decoder, it's OK to add more test cases and images to ensure the decoding correctness.

The Patch Code (only focus on `SDImageAVIFCoder.m` looks great for me. Do we need to merge and release a new Patch version ?

**Comment by ledyba-z** [comment]
Sorry to be late! (I have got in to server-side troubles, and resolved them....)

These tests images are focusing on testing YUV ⇔ RGB conversion functions, I added.

> The Patch Code (only focus on SDImageAVIFCoder.m looks great for me. Do we need to merge and release a new Patch version ?

Thanks! Yes, please release a new version (anyway this patch resolves a bug).

After this patch will be merged, I am going to send next patch, that makes decoder to output grayscale images for monochrome images (related to https://github.com/SDWebImage/SDWebImage/pull/2907).

However, it takes some time to prepare additional test images and debugging (~10 days?), so I think it is nice timing to release new version.

**Comment by dreampiggy** [comment]
Seems the test case not so stable ? The newer push (only updated Readme.md) cause the test case failed.

https://github.com/SDWebImage/SDWebImageAVIFCoder/runs/467123380

> ++ compare -metric PSNR kimono.png decoded/kimono.avif.png NULL:
> ++ true
> + score=34.7934
>  * kimono.avif: 34.7934
> + echo ' * kimono.avif: 34.7934'
> ++ echo '34.7934 >= 35.0'
> ++ bc -l
. + test 0 -eq 0
> + exit -1
> ##[error]Process completed with exit code 255.

**Comment by ledyba-z** [comment]
@dreampiggy 
Thanks to merge!
 
> Seems the test case not so stable ?
> The newer push (only updated Readme.md) cause the test case failed.

Ah, this test uses our [sample images](https://github.com/link-u/avif-sample-images), and I recently updated them to set correct color information. I think this change causes the problem.

It looks libavif can't handle color information correctly. So, I am going to send a patch to libavif.

**Comment by ledyba-z** [comment]
> Seems the test case not so stable ? The newer push (only updated Readme.md) cause the test case failed.

https://github.com/AOMediaCodec/libavif/pull/82 will resolve this issue.

**Comment by ledyba-z** [comment]
https://github.com/AOMediaCodec/libavif/pull/82 was merged, and v0.5.7 was released!

@dreampiggy could you upgrade libavif?

**Comment by dreampiggy** [comment]
I'll bump the version of libavif-Xcode soon.

**Comment by dreampiggy** [comment]
One strange issue. I already watch the libavif GitHub repo notification, but when the new releases come, no any notification ?

Or does GitHub's `Watch Release Only` feature only useful for the manual created release, but not the raw Git tag ?

image

**Comment by ledyba-z** [comment]
@dreampiggy 

Thank you!

> Or does GitHub's Watch Release Only feature only useful for the manual created release, but not the raw Git tag ?

Unfortunately, it may be so:

> It appears that "watch releases only" doesn't follow tags and many projects use only tags for announcing new versions. While https://newreleases.io sends notifications for tags too, it also has several version filtering options, based on regex expressions, pre and updated releases. It also offers email frequency options. 
>
> Watch only for release tags · Issue #111 · dear-github/dear-github
> https://github.com/dear-github/dear-github/issues/111

**Pull request merged**
